    steps:
    - name: 'gcr.io/cloud-builders/docker'
      args:
      - 'pull'
      - 'ghcr.io/nordinian/aiapi.services:aiapi-alpha'
    - name: 'gcr.io/cloud-builders/docker'
      args:
      - 'tag'
      - 'ghcr.io/nordinian/aiapi.services:aiapi-alpha'
      - 'us-west1-docker.pkg.dev/aiapi-services/aiapi-services/aiapi-services:alpha'

    images:
    - 'us-west1-docker.pkg.dev/aiapi-services/aiapi-services/aiapi-services:alpha'

    options:
      logging: CLOUD_LOGGING_ONLY
