    steps:
    - name: 'gcr.io/cloud-builders/docker'
      args:
      - 'build'
      - '-t'
      - 'us-west1-docker.pkg.dev/aiapi-services/aiapi-services/aiapi-services:latest'
      - '.'

    images:
    - 'us-west1-docker.pkg.dev/aiapi-services/aiapi-services/aiapi-services:latest'

    options:
      logging: CLOUD_LOGGING_ONLY
